onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /unpipelined_risc/clk
add wave -noupdate /unpipelined_risc/rst_external
add wave -noupdate /unpipelined_risc/rst
add wave -noupdate /unpipelined_risc/instruction
add wave -noupdate /unpipelined_risc/PC_out
add wave -noupdate /unpipelined_risc/MUX_J_B_out
add wave -noupdate /unpipelined_risc/A
add wave -noupdate /unpipelined_risc/B
add wave -noupdate /unpipelined_risc/ALU_in_A
add wave -noupdate /unpipelined_risc/ALU_in_B
add wave -noupdate /unpipelined_risc/reg_out_B
add wave -noupdate /unpipelined_risc/MUX_reg_addr_out
add wave -noupdate /unpipelined_risc/MUX_reg_data_out
add wave -noupdate /unpipelined_risc/ALU_control_out
add wave -noupdate /unpipelined_risc/ALU_out
add wave -noupdate /unpipelined_risc/mem_out
add wave -noupdate /unpipelined_risc/sign_extend_out
add wave -noupdate /unpipelined_risc/ALU_zero
add wave -noupdate /unpipelined_risc/shift_j_out
add wave -noupdate /unpipelined_risc/MUX_J_B_in
add wave -noupdate /unpipelined_risc/MUX_PC_out
add wave -noupdate /unpipelined_risc/sign_extend_out_shifted
add wave -noupdate /unpipelined_risc/PC_write_cond_c
add wave -noupdate /unpipelined_risc/PC_write_c
add wave -noupdate /unpipelined_risc/I_or_D_c
add wave -noupdate /unpipelined_risc/mem_read_c
add wave -noupdate /unpipelined_risc/mem_write_c
add wave -noupdate /unpipelined_risc/mem_to_reg_c
add wave -noupdate /unpipelined_risc/IR_write_c
add wave -noupdate /unpipelined_risc/PC_source_c
add wave -noupdate /unpipelined_risc/ALU_op_c
add wave -noupdate /unpipelined_risc/ALU_src_A_c
add wave -noupdate /unpipelined_risc/ALU_src_B_c
add wave -noupdate /unpipelined_risc/reg_write_c
add wave -noupdate /unpipelined_risc/reg_dst_c
add wave -noupdate /unpipelined_risc/PC_Write_Cond_N_c
add wave -noupdate /unpipelined_risc/word_byte
add wave -noupdate /unpipelined_risc/wr_done
add wave -noupdate /unpipelined_risc/rd_ready
add wave -noupdate /unpipelined_risc/initialize
add wave -noupdate /unpipelined_risc/dump
add wave -noupdate /unpipelined_risc/write_pc
add wave -noupdate /unpipelined_risc/pc_next
add wave -noupdate /unpipelined_risc/IO_mux_out
TreeUpdate [SetDefaultTree]
configure wave -namecolwidth 282
configure wave -valuecolwidth 246
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {1142 ps}
